In [276]:
import numpy as np

In [277]:
sales = [[0, 5, 155, 0, 518], [0, 1827, 616, 317, 325]]

In [278]:
sales_array = np.array(sales)
sales_array = sales_array+2
sales_array

array([[   2,    7,  157,    2,  520],
       [   2, 1829,  618,  319,  327]])

In [279]:
quantity = sales_array[0,]
prices = sales_array[1,]
print(quantity)
print(prices)

[  2   7 157   2 520]
[   2 1829  618  319  327]


In [280]:
l = prices*quantity
print(l)

[     4  12803  97026    638 170040]


In [281]:
sales_array = sales_array-2
print(sales_array)
sales_array != 0

[[   0    5  155    0  518]
 [   0 1827  616  317  325]]


array([[False,  True,  True, False,  True],
       [False,  True,  True,  True,  True]])

In [282]:
sales_array[sales_array != 0]

array([   5,  155,  518, 1827,  616,  317,  325])

In [283]:
sales_array[(sales_array > 100) & (sales_array < 400)]

array([155, 317, 325])

In [284]:
gthan100 = sales_array > 100
sthan400 = sales_array < 400
print(gthan100)
print(sthan400)

sales_array[gthan100 & sthan400]

[[False False  True False  True]
 [False  True  True  True  True]]
[[ True  True  True  True False]
 [ True False False  True  True]]


array([155, 317, 325])

In [285]:
mask = (sales_array > 100) & (sales_array < 400)
print(mask)
sales_array[mask]

[[False False  True False False]
 [False False False  True  True]]


array([155, 317, 325])

In [286]:
sales_array = sales_array[(sales_array > 500) | (sales_array == 0)]
products = np.array(["Fruits", " vegetables", "cereal",
                    "diary", "eggs", "alomnuts"])

products[sales_array > 0]

array(['cereal', 'eggs', 'alomnuts'], dtype='<U11')

In [287]:
sales_array[sales_array == 0] = 45
sales_array

array([  45,   45,  518,   45, 1827,  616])

WHERE FUNCTION AND PARAMETER


In [288]:
inventory_array = np.array([12, 102, 18, 0, 0])
products = products[:5]
products

array(['Fruits', ' vegetables', 'cereal', 'diary', 'eggs'], dtype='<U11')

In [289]:
np.where(inventory_array <= 0, 'out of stock', products)

array(['Fruits', ' vegetables', 'cereal', 'out of stock', 'out of stock'],
      dtype='<U12')

In [290]:
sales_array = np.array([[0, 5, 155, 0, 518], [0, 1827, 616, 317, 325]])

sales_array

array([[   0,    5,  155,    0,  518],
       [   0, 1827,  616,  317,  325]])

In [291]:
print(sales_array.sum())

np.sum(sales_array)

3763


3763

In [292]:
print(sales_array.max())
print(sales_array.min())

print(np.max(sales_array))
print(np.min(sales_array))

1827
0
1827
0


In [293]:
sales_array.mean()

376.3

In [294]:
sales_array.std()

529.1366647662965

In [295]:
np.median(sales_array)

236.0

In [296]:
print(sales_array[0, :].sum())
sales_array.sum(axis=1)

678


array([ 678, 3085])

In [297]:
np.percentile(sales_array,  50)

236.0

SORTING


In [298]:
np.sort(sales_array)

array([[   0,    0,    5,  155,  518],
       [   0,  317,  325,  616, 1827]])

In [299]:
sales_array

array([[   0,    5,  155,    0,  518],
       [   0, 1827,  616,  317,  325]])

In [300]:
sales_array.sort()
sales_array

array([[   0,    0,    5,  155,  518],
       [   0,  317,  325,  616, 1827]])

In [301]:
sales_array = np.array([[0, 5, 155, 0, 518], [0, 1827, 616, 317, 325]])

sales_array.sort(axis=0)
sales_array

array([[   0,    5,  155,    0,  325],
       [   0, 1827,  616,  317,  518]])

In [302]:
sales_array[:, ::-1]  # 2d array is reversed

array([[ 325,    0,  155,    5,    0],
       [ 518,  317,  616, 1827,    0]])