In [48]:
import numpy as np

In [49]:
ones = np.ones((5, 2), 'str')  # array of ones
print(ones)

[['1' '1']
 ['1' '1']
 ['1' '1']
 ['1' '1']
 ['1' '1']]


In [50]:
zeros = np.zeros((3, 2), 'float')  # array of zeros
print(zeros)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [51]:
np.arange(0, 10, 2)  # here 10 exclusive

array([0, 2, 4, 6, 8])

In [52]:
ones.reshape(2, 5)  # This can only be shaped the metrics but it cannot change the size or the data type means it cannot change properties of the matrix You don't be able to make a 5 by 5 metrics as their only 10 elements but it can make one by 10 or 10 by 1 matrix But it won't be able to change the data type of the matrix from string to integer

array([['1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1']], dtype='<U1')

In [56]:
np.linspace(0, 10, 6, 'int')

array([ 0.,  2.,  4.,  6.,  8., 10.])