In [1]:
import numpy as np

In [2]:
array = np.array(range(5, 10))

print(array)

[5 6 7 8 9]


In [3]:
array_2d = np.array([range(0, 5), range(5, 10)])
print(array_2d)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [4]:
array_2d.shape

(2, 5)

In [5]:
array_2d.size

10

In [6]:
print(array_2d.T)

[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]
