### Package Imports


In [3]:
import numpy as np

# Assignment 1: Array Basics

Hi there,

Can you import Numpy and convert the following list comprehension (I just learned about comprehensions in an awesome course by Maven) into an array?

Once you've done that report the following about the array:

- The number of dimensions
- The shape
- The number of elements in the array
- The type of data contained inside


In [4]:
my_list = [x * 10 for x in range(1, 11)]
arr = np.array(my_list)
arr

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [5]:
arr.ndim

1

In [6]:
arr.shape

(10,)

In [7]:
arr.size

10

In [8]:
arr.dtype

dtype('int32')

# Assignment 2: Array Creation

Thanks for your help with the first piece - I'm starting to understand some of the key differences between base Python data types and NumPy arrays.

Does NumPy have anything like the range() function from base Python?

If so:

- create the same array from assignment 1 using a NumPy function.
- Make it 5 rows and 2 columns.
- It's ok if the datatype is float or int.


In [9]:
new_arr = np.linspace(10, 100, 10, dtype='int')
new_arr

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

Looking good so far! One of our data scientists asked about random number generation in NumPy.

Can you create a 3x3 array of random numbers between 0 and 1? Use a random state of 2022.

Store the random array in a variable called `random_array`.


In [10]:
from numpy.random import default_rng as drng

rng = drng(12)

random_array = rng.random((3, 3))
random_array

array([[0.25082446, 0.94675294, 0.18932038],
       [0.17929141, 0.34988924, 0.23054125],
       [0.67044574, 0.11507938, 0.89630937]])

# Assignment 3: Accessing Array Data

Slice and index the `random_array` we created in the previous exercise. Perform the following:

- Grab the first two 'rows' of the array
- Grab the entire first column
- Finally, grab the second selement of the third row.

Thanks!


In [11]:
random_array[:2, :]

array([[0.25082446, 0.94675294, 0.18932038],
       [0.17929141, 0.34988924, 0.23054125]])

In [12]:
random_array[:, 0]

array([0.25082446, 0.17929141, 0.67044574])

In [13]:
random_array[2, 1]

0.11507938212344748

# Assignment 4: Arithmetic Operations


The creativity of our marketing team knows no bounds!

They've asked us to come up with a simple algorithm to provide a random discount to our list of prices below.

Before we do that,

- Add a 5 dollar shipping fee to each price. Call this array `total`.

Once we have that, we want to use the random_array created in assignment 2 and apply them to the 6 prices.

- Grab the first 6 numbers from `random_array`, reshape it to one dimension. Call this `discount_pct`.
- Subtract `discount_pct` FROM 1, store this in `pct_owed`.
- Multiply `pct_owed` by `total` to get the final amount owed.


In [14]:
prices = np.array([5.99, 6.99, 22.49, 99.99, 4.99, 49.99])
total = prices+5
total

array([ 10.99,  11.99,  27.49, 104.99,   9.99,  54.99])

In [15]:
discount_pct = random_array[:2].reshape(1, 6)
discount_pct

array([[0.25082446, 0.94675294, 0.18932038, 0.17929141, 0.34988924,
        0.23054125]])

In [16]:
pct_owed = 1-discount_pct
pct_owed

array([[0.74917554, 0.05324706, 0.81067962, 0.82070859, 0.65011076,
        0.76945875]])

In [17]:
total*pct_owed

array([[ 8.23343921,  0.63843222, 22.28558263, 86.16619482,  6.49460649,
        42.31253685]])

# Assignment 5: Filtering Arrays

Filter the product array to only include those with prices greater than 25.

Modify your logic to include cola, despite it not having a price greater than 25.
Store the elements returned in an array called `fancy_feast_special`.

Next, create a shipping cost array where the cost is 0 if price is greater than 20, and 5 if not.


In [18]:
products = np.array(
    ["salad", "bread", "mustard", "rare tomato", "cola", "gourmet ice cream"]
)

products

array(['salad', 'bread', 'mustard', 'rare tomato', 'cola',
       'gourmet ice cream'], dtype='<U17')

In [19]:
products[prices > 25]

array(['rare tomato', 'gourmet ice cream'], dtype='<U17')

In [20]:
fancy_feast_special = products[(prices > 25) | (products == 'cola')]
fancy_feast_special

array(['rare tomato', 'cola', 'gourmet ice cream'], dtype='<U17')

In [21]:
shipping_cst_arr = np.where(prices > 20, 0, 5)
shipping_cst_arr

array([5, 5, 0, 0, 5, 0])

# Assignment 6: Aggregating and Sorting Arrays

First, grab the top 3 highest priced items in our list.

Then, calculated the mean, min, max, and median of the top three prices.

Finally, calculate the number of unique price tiers in our `price_tiers` array.


In [22]:
prices = np.array([5.99, 6.99, 22.49, 99.99, 4.99, 49.99])

prices

array([ 5.99,  6.99, 22.49, 99.99,  4.99, 49.99])

In [23]:
prices.sort()
prices = prices[::-1][:3]
prices

array([99.99, 49.99, 22.49])

In [24]:
print(prices.mean())
prices.max()

57.49


99.99

In [25]:
print(prices.min())
np.median(prices)
np.percentile(prices, 50)

22.49


49.99

In [26]:
price_tiers = np.array(["budget", "budget", "mid-tier",
                       "luxury", "mid-tier", "luxury"])

In [27]:
np.unique(price_tiers)

array(['budget', 'luxury', 'mid-tier'], dtype='<U8')

# Assignment 7: Bringing it All Together

Ok, final NumPy task - let's read in some data with the help of Pandas.

Our data scientist provided the code to read in a csv as a Pandas dataframe, and has converted the two columns of interest to arrays.

- Filter `sales_array` down to only sales where the product family was produce.

- Then, randomly sample roughly half (random number < .5) of the produce sales and report the mean and median sales. Use a random seed of 2022.

- Finally, create a new array that has the values 'above_both', 'above_median', and 'below_both' based on whether the sales were above the median and mean of the sample, just above the median of the sample, or below both the median and mean of the sample.


In [33]:
import pandas as pd
import numpy as np

retail_df = pd.read_csv(
    "../retail/retail_2016_2017.csv", skiprows=range(1, 11000), nrows=1000
)

family_array = np.array(retail_df["family"])
sales_array = np.array(retail_df["sales"])
sales_array.size
family_array.size

1000

In [29]:
produce_array = sales_array[family_array == 'PRODUCE']
sales_array

array([1.77000000e+02, 3.60000000e+01, 2.29106000e+03, 1.60000000e+01,
       2.00000000e+00, 1.20000000e+01, 7.00000000e+00, 0.00000000e+00,
       1.94000000e+02, 3.00000000e+00, 2.00000000e+00, 6.00000000e+00,
       4.60000000e+01, 1.00000000e+00, 2.18416000e+02, 1.84000000e+02,
       4.00000000e+00, 1.00000000e+00, 2.63230000e+02, 5.10000000e+01,
       1.66239400e+03, 0.00000000e+00, 6.53600030e+00, 1.00000000e+01,
       0.00000000e+00, 2.00000000e+00, 3.03300000e+03, 0.00000000e+00,
       1.61000000e+02, 1.20000000e+01, 7.18000000e+02, 2.67000000e+02,
       2.80000000e+02, 2.70000000e+01, 4.70000000e+01, 2.45300000e+03,
       2.00000000e+00, 1.00000000e+00, 2.20000000e+01, 8.00000000e+00,
       0.00000000e+00, 1.39000000e+02, 1.00000000e+00, 0.00000000e+00,
       2.00000000e+00, 4.60000000e+01, 1.00000000e+00, 1.68847000e+02,
       1.90000000e+02, 0.00000000e+00, 0.00000000e+00, 2.18873000e+02,
       4.60000000e+01, 4.47064000e+02, 0.00000000e+00, 4.00000000e+00,
      

In [30]:
from numpy.random import default_rng

rng = default_rng
samples = sales_array.rng.random()

AttributeError: 'numpy.ndarray' object has no attribute 'rng'