pandas series basic


In [50]:
import numpy as np
import pandas as pd

array = np.arange(5, 10)
array

array([5, 6, 7, 8, 9])

In [51]:
# pandas array can only be 1 D

# pd.Series(np.arange(6).reshape(3, 2))

In [52]:
# naming pandas arrays

sales_series = pd.Series(
    np.array([0, 5, 155, 0, 518, 0, 1827, 616, 317, 325]), name='sales')

sales_series

0       0
1       5
2     155
3       0
4     518
5       0
6    1827
7     616
8     317
9     325
Name: sales, dtype: int32

In [53]:
sales_series.values

array([   0,    5,  155,    0,  518,    0, 1827,  616,  317,  325])

In [54]:

# i can do custom indexing

sales_series.index = [3, 4, 5, 6, 7, 8, 14, 16, 67, 10]
sales_series.index

Index([3, 4, 5, 6, 7, 8, 14, 16, 67, 10], dtype='int64')

In [55]:
# i can change name any time

sales_series.name = 'new sales'
sales_series.name

'new sales'

In [56]:
# aggregation will be similar as like numpy arrays

print(sales_series.sum())
print(sales_series.mean())
print(sales_series.std())
print(sales_series.median())

3763
376.3
557.759018055488
236.0


CONVERTING DATA TYPE USING ASTYPE FUNCTION()


In [57]:
# data in int
sales_series.astype

<bound method NDFrame.astype of 3        0
4        5
5      155
6        0
7      518
8        0
14    1827
16     616
67     317
10     325
Name: new sales, dtype: int32>

In [58]:
sales_series_float = sales_series.astype('float')
sales_series_float

3        0.0
4        5.0
5      155.0
6        0.0
7      518.0
8        0.0
14    1827.0
16     616.0
67     317.0
10     325.0
Name: new sales, dtype: float64

In [59]:
sales_series_ob = sales_series_float.astype('object')
sales_series_ob

3        0.0
4        5.0
5      155.0
6        0.0
7      518.0
8        0.0
14    1827.0
16     616.0
67     317.0
10     325.0
Name: new sales, dtype: object

In [60]:

sales_series_str = sales_series_ob.astype('string')
sales_series_str

3        0.0
4        5.0
5      155.0
6        0.0
7      518.0
8        0.0
14    1827.0
16     616.0
67     317.0
10     325.0
Name: new sales, dtype: string

In [61]:
# can not convert from string to int but other conversion is valid
# sales_series_str.astype('int')


print(sales_series_str.astype('float'))
print(sales_series_str.astype('object'))

3        0.0
4        5.0
5      155.0
6        0.0
7      518.0
8        0.0
14    1827.0
16     616.0
67     317.0
10     325.0
Name: new sales, dtype: float64
3        0.0
4        5.0
5      155.0
6        0.0
7      518.0
8        0.0
14    1827.0
16     616.0
67     317.0
10     325.0
Name: new sales, dtype: object


In [62]:
# sales_series_str.sum()
# can not canculate sum ,mean std etc for str array

INDEX SLICING


In [63]:
sales = [0, 5, 155, 0, 518]
sales_series = pd.Series(sales, name="sales")
sales_series

0      0
1      5
2    155
3      0
4    518
Name: sales, dtype: int64

In [64]:
print(sales_series[1])
print(sales_series[1:3])
print(sales_series[::2])

5
1      5
2    155
Name: sales, dtype: int64
0      0
2    155
4    518
Name: sales, dtype: int64


In [65]:
sales = [0, 5, 155, 0, 518]
items = ['coffes ', 'bananas', 'teas', 'coconut', 'sugar']

sales_series = pd.Series(sales, index=items, name='items with sales')
sales_series

coffes       0
bananas      5
teas       155
coconut      0
sugar      518
Name: items with sales, dtype: int64

In [66]:
print(sales_series['teas'])
print(sales_series['bananas': 'coconut'])
print(sales_series[1: 3])

155
bananas      5
teas       155
coconut      0
Name: items with sales, dtype: int64
bananas      5
teas       155
Name: items with sales, dtype: int64


ILOC METHOD MUCH FASTER SUITABLE FOR PANDAS DATAFRAMES WHERE WE WILL WORK WITH COLOUM AND AS WELL AS ROWS


In [67]:
print(sales_series)
print(sales_series.iloc[1:])
sales_series['bananas']

coffes       0
bananas      5
teas       155
coconut      0
sugar      518
Name: items with sales, dtype: int64
bananas      5
teas       155
coconut      0
sugar      518
Name: items with sales, dtype: int64


5

In [68]:
print(sales_series['bananas':'coconut'])

print(sales_series[['bananas', 'coconut', 'teas']])

print(sales_series[[1, 3, 4]])

bananas      5
teas       155
coconut      0
Name: items with sales, dtype: int64
bananas      5
coconut      0
teas       155
Name: items with sales, dtype: int64
bananas      5
coconut      0
sugar      518
Name: items with sales, dtype: int64


LOC FUNCTION AND HOW IT WORKS
LOC METHID IS INCLUSIVE FROM START TO STOP


In [69]:
sales_series

coffes       0
bananas      5
teas       155
coconut      0
sugar      518
Name: items with sales, dtype: int64

In [70]:
sales_series.loc["bananas"]

5

In [71]:
sales_series.loc['bananas':'coconut']

bananas      5
teas       155
coconut      0
Name: items with sales, dtype: int64

In [72]:
sales_series.index = [0, 2, 3, 100, 5]
sales_series

0        0
2        5
3      155
100      0
5      518
Name: items with sales, dtype: int64

In [73]:
sales_series.loc[0:3]
sales_series.reset_index(drop=True)

0      0
1      5
2    155
3      0
4    518
Name: items with sales, dtype: int64

RESETING INDEX


In [74]:
my_series = pd.Series([1, 2, 3, 4, 5], index=[
                      'day 1', 'day 1', 'day 1', 'day 2', 'day 2'])

my_series

day 1    1
day 1    2
day 1    3
day 2    4
day 2    5
dtype: int64

In [75]:
my_series['day 1':'day 2']

# this will return every thing

day 1    1
day 1    2
day 1    3
day 2    4
day 2    5
dtype: int64

In [76]:
# reset_index gives data frame

my_series.reset_index()

index  0
0  day 1  1
1  day 1  2
2  day 1  3
3  day 2  4
4  day 2  5

In [77]:
my_series.reset_index(drop=True).loc[1:3]

1    2
2    3
3    4
dtype: int64

SORTING AND FILTERING


In [78]:
sales_series = pd.Series([0, 5, 155, 0, 518], index=[
                         'coffe', 'coffee', 'tea', 'coconut', 'sugar'], name='sales array')

sales_series

coffe        0
coffee       5
tea        155
coconut      0
sugar      518
Name: sales array, dtype: int64

In [79]:
# return true false
sales_series > 0

coffe      False
coffee      True
tea         True
coconut    False
sugar       True
Name: sales array, dtype: bool

In [80]:
# returns values of sales where the condition is true
sales_series[sales_series > 0]

coffee      5
tea       155
sugar     518
Name: sales array, dtype: int64

In [81]:
mask = (sales_series.index == "coffee") & (sales_series > 0)
sales_series[mask]

coffee    5
Name: sales array, dtype: int64

SORITNG


In [82]:
sales_series
# sorting is not in place
# by default ascending
SortedSalesSeriesIdx = sales_series.sort_index()
SortedSalesSeriesVal = sales_series.sort_values()

print(SortedSalesSeriesIdx)


print(SortedSalesSeriesVal)

coconut      0
coffe        0
coffee       5
sugar      518
tea        155
Name: sales array, dtype: int64
coffe        0
coconut      0
coffee       5
tea        155
sugar      518
Name: sales array, dtype: int64


In [83]:
# code in decending order

sales_series.sort_values(ascending=False)

sugar      518
tea        155
coffee       5
coffe        0
coconut      0
Name: sales array, dtype: int64

ARITHMATIC OPERATION


In [84]:
my_series = pd.Series([1, np.NaN, 2, 3, 4], index=[
                      'day 0', 'day 1', 'day 2', 'day 3', 'day 4'])
my_series

day 0    1.0
day 1    NaN
day 2    2.0
day 3    3.0
day 4    4.0
dtype: float64

In [85]:
my_series+2

day 0    3.0
day 1    NaN
day 2    4.0
day 3    5.0
day 4    6.0
dtype: float64

In [86]:
my_series+3//2

day 0    2.0
day 1    NaN
day 2    3.0
day 3    4.0
day 4    5.0
dtype: float64

In [87]:
# if there is a NaN then fill the value 1 in place of Nan and add 3
my_series.add(3, fill_value=1)

day 0    4.0
day 1    4.0
day 2    5.0
day 3    6.0
day 4    7.0
dtype: float64

STRING METHOD


In [88]:
prices = pd.Series(['$3.99', '$5.99', '$22.99', '$7.99',
                   '$33.99'], index=[0, 1, 2, 3, 4])

In [89]:
# Strip $ sign

prices.str.strip('$').astype(float)+2

0     5.99
1     7.99
2    24.99
3     9.99
4    35.99
dtype: float64

In [90]:
days_array = pd.Series(['day 1', 'day 2',
                        'day 3', 'day 4'], index=[1, 2, 3, 4])
days_array

1    day 1
2    day 2
3    day 3
4    day 4
dtype: object

In [91]:
days_array.str[-1].astype(int)

1    1
2    2
3    3
4    4
dtype: int32

In [92]:
# split method can return array

print(days_array.str.split(" "))

# days array should return

print(days_array.str.split(" ", expand=True))

1    [day, 1]
2    [day, 2]
3    [day, 3]
4    [day, 4]
dtype: object
     0  1
1  day  1
2  day  2
3  day  3
4  day  4


aggregate numerical Series


In [93]:
sales_series = sales_series.rename(index={'coffe': 'coffee'})
print(sales_series.loc['coffee'].sum())

print(sales_series.median())
print(sales_series.mean())
print(sales_series.quantile([.25, .5, .75]))
print()
print(sales_series.count())

5
5.0
135.6
0.25      0.0
0.50      5.0
0.75    155.0
Name: sales array, dtype: float64

5


AGGREGATE CATEGORICAL SERIES


In [94]:
sales_series

coffee       0
coffee       5
tea        155
coconut      0
sugar      518
Name: sales array, dtype: int64

In [95]:
# returns array of unique items

print(sales_series.unique())

# reuturn integer count of unique elements

print(sales_series.nunique())

# returns a series with unique elements and their count

print(sales_series.value_counts())

[  0   5 155 518]
4
sales array
0      2
5      1
155    1
518    1
Name: count, dtype: int64


HANDELING MISSING DATA


In [96]:
my_series = pd.Series([1, 2, 3, pd.NA, 4, 5], index=[0, 1, 2, 3, 4, 5])
my_series

0       1
1       2
2       3
3    <NA>
4       4
5       5
dtype: object

In [102]:
print(my_series.isna())
my_series.isna().sum()

my_series.value_counts(dropna=False)

0    False
1    False
2    False
3     True
4    False
5    False
dtype: bool


1       1
2       1
3       1
<NA>    1
4       1
5       1
Name: count, dtype: int64

In [103]:
my_series.fillna(my_series.mean())

0    1.0
1    2.0
2    3.0
3    3.0
4    4.0
5    5.0
dtype: float64